"""OGSE parity tests for C4CylinderGaussianPhaseApproximation.signal_lm().

Three tests establishing that the signal_lm / gamma_lm analytical path has
full parity with PGSE for OGSE waveforms:

Test 1 — analytical, no fixture:
    Build a cosine OGSE waveform via from_waveform(), compute signal_lm(), and
    reconstruct E(θ) at multiple polar angles via SH evaluation.  Compare
    against _ogse_cosine_cylinder_signal() (the exact closed-form GPA formula).
    Tolerance: 1e-3 (fast-eigenmode + waveform discretization).

Test 2 — analytical, no fixture:
    Build a *rotating* cosine OGSE waveform (gradient direction rotates 90°
    over the echo time while oscillating at 50 Hz) via from_waveform(), compute
    signal_lm(), and reconstruct E(θ) at GL angles.  Compare against the IIR
    numerical GPA path (_ogse_numerical_cylinder_signal) at each angle.
    This waveform has no closed-form reference other than the gamma_lm path.
    Tolerance: 2e-3 (numerical IIR vs analytical γ_lm + SH reconstruction).

Test 3 — MC-backed dispersed, requires fixture:
    Load fixtures_ogse_dispersed.npz (generated by
    benchmarks/cylinder_fixtures/generate_ogse_dispersed_fixtures.py).
    For each waveform type × G_max × R × κ, compare
        signal_lm() + dispersed_signal_from_E_lm()
    against the Monte Carlo reference signal.  Tolerance: 0.02.

Fixture generation (one-time, CPU, ~10 min for 3 radii):
    cd benchmarks/cylinder_fixtures
    python generate_ogse_dispersed_fixtures.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pytest
from numpy.polynomial.legendre import leggauss

from dmipy_fit.core.acquisition_scheme import AcquisitionScheme
from dmipy_fit.core.constants import CONSTANTS
from dmipy_fit.signal_models.cylinder_models import (
    C4CylinderGaussianPhaseApproximation,
    _ogse_cosine_cylinder_signal,
    _ogse_numerical_cylinder_signal,
    dispersed_signal_from_E_lm,
    watson_odf_lm,
)

GAMMA       = CONSTANTS['water_gyromagnetic_ratio']
D_PERP      = 1.7e-9    # m²/s
LAMBDA_PAR  = 1.7e-9    # m²/s
FREQ_HZ     = 50
N_CYCLES    = 2
T_TOTAL     = N_CYCLES / FREQ_HZ   # 0.040 s
OMEGA       = 2.0 * np.pi * FREQ_HZ
DT_WF       = 1e-4                  # s
DIAM_UM     = 2.0                   # µm (fast-eigenmode valid: α₁T ≈ 57)
DIAM_M      = DIAM_UM * 1e-6
G_AMP       = 0.10                  # T/m

import os
# Offline-generated MC fixtures, shipped alongside these tests (see mc_fixtures/README.md).
FIXTURE_DIR = Path(os.environ.get(
    "DMIPY_FIXTURE_DIR", str(Path(__file__).parent / "mc_fixtures")))
FIXTURE_NPZ = FIXTURE_DIR / "fixtures_ogse_dispersed.npz"

_ROOTS = C4CylinderGaussianPhaseApproximation._CYLINDER_TRASCENDENTAL_ROOTS


# ---------------------------------------------------------------------------
# Shared waveform builders
# ---------------------------------------------------------------------------

def _build_ogse_cosine_scheme(G_amp=G_AMP, along_z=True):
    """Single-measurement cosine OGSE scheme via from_waveform."""
    n_t = int(round(T_TOTAL / DT_WF)) + 1
    t   = np.arange(n_t) * DT_WF
    G   = np.zeros((n_t, 3), dtype=np.float32)
    axis = 2 if along_z else 0
    G[:, axis] = (G_amp * np.cos(OMEGA * t)).astype(np.float32)
    G_arr = G[np.newaxis]                     # (1, n_t, 3)
    grad_dir = np.zeros((1, 3))
    grad_dir[0, axis] = 1.0
    return AcquisitionScheme.from_waveform(G_arr, DT_WF, grad_dir,
                                           allow_unrefocused=True)


def _build_ogse_rotating_scheme(G_amp=G_AMP):
    """Single-measurement rotating cosine OGSE scheme via from_waveform.

    G(t) = G_amp * cos(2πft) * [cos(πt/T), sin(πt/T), 0].
    """
    n_t = int(round(T_TOTAL / DT_WF)) + 1
    t   = np.arange(n_t) * DT_WF
    env = G_amp * np.cos(OMEGA * t)
    rot = np.pi / 2.0 * t / T_TOTAL
    G   = np.zeros((n_t, 3), dtype=np.float32)
    G[:, 0] = (env * np.cos(rot)).astype(np.float32)
    G[:, 1] = (env * np.sin(rot)).astype(np.float32)
    G_arr = G[np.newaxis]
    grad_dir = np.array([[1.0 / np.sqrt(2.0), 1.0 / np.sqrt(2.0), 0.0]])
    return AcquisitionScheme.from_waveform(G_arr, DT_WF, grad_dir,
                                           allow_unrefocused=True)


# ---------------------------------------------------------------------------
# SH reconstruction helper
# ---------------------------------------------------------------------------

def _sh_at_polar_angles(E_lm_row, thetas):
    """Reconstruct SH signal at polar angles (φ=0), l_max=8 Tournier.

    Returns E_recon(θ_i) by evaluating the real SH basis at (θ_i, 0) and
    dotting with E_lm.

    Only l=0,2,4,6,8 terms contribute (E_lm is even in θ by construction).
    """
    from scipy.special import sph_harm_y as sph_harm
    import math

    l_max = 8
    n_lm  = (l_max + 1) * (l_max + 2) // 2
    assert len(E_lm_row) >= n_lm

    n_ang = len(thetas)
    Y     = np.zeros((n_ang, n_lm), dtype=np.float64)

    coef_idx = 0
    for l in range(0, l_max + 1, 2):
        for m in range(-l, l + 1):
            # Tournier real SH at (theta, phi=0)
            if m > 0:
                # Y_l^m real = sqrt(2) * Re(Y_l^m complex) at phi=0
                Y_cmplx = sph_harm(l, m, thetas, 0.0)      # (n, m, theta, phi)
                Y[:, coef_idx] = np.sqrt(2.0) * Y_cmplx.real
            elif m < 0:
                # sin(|m|*phi) = 0 at phi=0 → all-zero
                Y[:, coef_idx] = 0.0
            else:
                # m=0
                Y[:, coef_idx] = sph_harm(l, 0, thetas, 0.0).real
            coef_idx += 1

    return Y @ E_lm_row[:n_lm]


# ---------------------------------------------------------------------------
# Test 1: OGSE cosine — signal_lm fiber-angle scan vs analytical formula
# ---------------------------------------------------------------------------

def test_ogse_cosine_signal_lm_vs_analytical():
    """signal_lm fiber-angle reconstruction matches _ogse_cosine_cylinder_signal.

    Builds a cosine OGSE along ê_z as a free waveform, computes E_lm via
    signal_lm() (SH over fiber orientations), and reconstructs E at 9 polar
    angles θ ∈ (0, π/2].  Compares each E_recon(θ) against the closed-form
    GPA formula for the perpendicular component G_perp = G_amp * sin(θ) plus
    parallel Gaussian decay.
    """
    scheme = _build_ogse_cosine_scheme(G_amp=G_AMP, along_z=True)
    c4 = C4CylinderGaussianPhaseApproximation(
        diffusion_perpendicular=D_PERP, diameter=DIAM_M)

    E_lm = c4.signal_lm(scheme, diameter=DIAM_M, lambda_par=LAMBDA_PAR)
    assert E_lm.shape == (1, 45)

    thetas = np.linspace(np.pi / 18, np.pi / 2, 9)   # 10° … 90° from ê_z
    E_recon = _sh_at_polar_angles(E_lm[0], thetas)

    R = DIAM_M / 2.0
    for i, theta in enumerate(thetas):
        G_perp = G_AMP * np.sin(theta)
        # Perpendicular: closed-form Stepisnik GPA
        E_perp = _ogse_cosine_cylinder_signal(
            G_perp, OMEGA, T_TOTAL, D_PERP, R, _ROOTS)
        # Parallel: Gaussian b_par = b_total * cos²θ
        b_total = float(np.trace(scheme.btensor()[0]))
        b_par   = b_total * np.cos(theta) ** 2
        E_par   = np.exp(-b_par * LAMBDA_PAR)
        E_ref   = float(E_perp) * float(E_par)

        assert abs(E_recon[i] - E_ref) < 1e-3, (
            f"θ={np.degrees(theta):.0f}°: signal_lm={E_recon[i]:.5f}  "
            f"analytical={E_ref:.5f}  diff={abs(E_recon[i]-E_ref):.2e}"
        )


# ---------------------------------------------------------------------------
# Test 2: Rotating OGSE — signal_lm vs IIR numerical at each GL angle
# ---------------------------------------------------------------------------

def test_ogse_rotating_signal_lm_vs_iir():
    """Rotating cosine OGSE: signal_lm SH reconstruction matches IIR numerical.

    The gradient oscillates at 50 Hz while its direction rotates 90° in xy.
    No closed-form GPA formula exists for this waveform.  Comparison reference
    is the IIR numerical GPA path (_ogse_numerical_cylinder_signal) applied to
    the actual G(t) perpendicular component at each fiber angle.
    """
    scheme = _build_ogse_rotating_scheme(G_amp=G_AMP)
    c4 = C4CylinderGaussianPhaseApproximation(
        diffusion_perpendicular=D_PERP, diameter=DIAM_M)

    E_lm = c4.signal_lm(scheme, diameter=DIAM_M, lambda_par=LAMBDA_PAR)
    assert E_lm.shape == (1, 45)

    # GL quadrature angles (same as fixture generator)
    from scipy.special import roots_legendre
    gl_nodes, _ = roots_legendre(12)
    gl_nodes_u  = gl_nodes[gl_nodes > 0]
    thetas_gl   = np.arccos(gl_nodes_u)

    # Reconstruct E(θ, φ=0) from signal_lm
    E_recon = _sh_at_polar_angles(E_lm[0], thetas_gl)

    # Build G(t) waveform array for IIR comparison
    n_t = int(round(T_TOTAL / DT_WF)) + 1
    t   = np.arange(n_t) * DT_WF
    env = G_AMP * np.cos(OMEGA * t)
    rot = np.pi / 2.0 * t / T_TOTAL
    G_x = env * np.cos(rot)
    G_y = env * np.sin(rot)
    # G_z = 0

    def _Ry(theta):
        c, s = np.cos(theta), np.sin(theta)
        return np.array([[c, 0., s], [0., 1., 0.], [-s, 0., c]])

    R = DIAM_M / 2.0
    errors = []
    for i, theta in enumerate(thetas_gl):
        # Rotate the waveform by R_y(theta): fiber at angle theta from z
        # G_rot(t) = R_y(theta) @ G(t)
        Ry = _Ry(theta)
        G_vec = np.stack([G_x, G_y, np.zeros(n_t)], axis=-1)   # (n_t, 3)
        G_rot = G_vec @ Ry.T                                      # (n_t, 3)
        # Fiber along z: perpendicular component = G_rot[:, :2] projected onto radial
        # For the GPA cylinder the perpendicular is the 2D component in the xy-plane
        G_perp_mag = np.sqrt(G_rot[:, 0]**2 + G_rot[:, 1]**2)   # (n_t,) — scalar perp
        # IIR needs the 1D perpendicular gradient amplitude (scalar G_perp(t))
        # The cylinder GPA in 2D uses |G_perp(t)| as a signed signal via phase;
        # for the numerical IIR we need the signed projection.  Use x-component
        # of the rotated perpendicular (IIR integrates G(t)G(t') — sign cancels).
        G_perp_1d = G_rot[:, 0]   # x component of rotated waveform (perp to z-fiber)
        E_perp_iir = _ogse_numerical_cylinder_signal(G_perp_1d, DT_WF, D_PERP, R, _ROOTS)

        # Parallel component: z-component of rotated waveform
        G_par_1d = G_rot[:, 2]    # (n_t,)
        # b_par = γ² ∫q_par(t)² dt = γ² × (cumulative integral of G_par)² integral
        q_par = GAMMA * np.cumsum(G_par_1d) * DT_WF
        b_par = float(np.trapezoid(q_par**2, dx=DT_WF))
        E_par = np.exp(-b_par * LAMBDA_PAR)

        E_ref = float(E_perp_iir) * float(E_par)
        errors.append(abs(E_recon[i] - E_ref))

        print(f"θ={np.degrees(theta):.1f}°: signal_lm={E_recon[i]:.5f}  "
              f"IIR={E_ref:.5f}  diff={errors[-1]:.2e}")

    assert max(errors) < 2e-3, (
        f"Max |signal_lm - IIR|={max(errors):.2e} > 2e-3\n"
        f"Per-angle errors: {[f'{e:.2e}' for e in errors]}"
    )


# ---------------------------------------------------------------------------
# Test 3: MC-backed dispersed (requires fixture)
# ---------------------------------------------------------------------------

def _require_fixture():
    if not FIXTURE_NPZ.exists():
        pytest.skip(
            f"OGSE dispersed fixture not found: {FIXTURE_NPZ}\n"
            "Run: cd benchmarks/cylinder_fixtures && "
            "python generate_ogse_dispersed_fixtures.py"
        )


RADII_UM     = [1.0, 2.0]
# R=3µm excluded: α₁T ≈ 25 at 40ms — fast-eigenmode breaks down at high G
# (OGSE at 50 Hz is more restriction-sensitive than PGSE at same G_max,
# so GPA errors exceed 0.02 for G≥0.3 T/m at R=3µm).
G_MAX_LEVELS = [0.05, 0.10, 0.20, 0.30]
KAPPA_VALUES = [1, 5, 20, 100]
WF_NAMES     = ["ogse_cosine"]
# ogse_rotating is excluded from MC-dispersed test: the rotating waveform lives
# in the xy-plane, so E(n̂) depends on both θ and φ of the fiber orientation.
# The fixture generator's Legendre (m=0) fit discards φ-dependence, making the
# MC reference incorrect for non-axially-symmetric waveforms.  The rotating
# OGSE is validated analytically in test_ogse_rotating_signal_lm_vs_iir.

MU_Z = np.array([0., 0., 1.])

TOL = 0.02   # MC noise floor at 500k walkers


@pytest.mark.parametrize("R_um",    RADII_UM)
@pytest.mark.parametrize("G_max",   G_MAX_LEVELS)
@pytest.mark.parametrize("kappa",   KAPPA_VALUES)
@pytest.mark.parametrize("wf_name", WF_NAMES)
def test_ogse_dispersed_vs_mc_fixture(wf_name, G_max, kappa, R_um):
    """signal_lm + dispersed_signal_from_E_lm matches MC dispersed fixture.

    Fixture provides Watson-dispersed signals from 500k-walker MC trajectories
    at Gauss-Legendre angles (Legendre RH fit + Watson SH convolution).
    Analytical path: C4.signal_lm() for a single OGSE measurement along ê_z,
    dispersed via the SH inner product with the same Watson ODF.
    """
    _require_fixture()

    data = np.load(FIXTURE_NPZ, allow_pickle=False)
    key  = (f"{wf_name}__G{int(G_max*1000):04d}mTm"
            f"__R{int(R_um*100):04d}nm__kappa{kappa:04d}__dispersed")
    if key not in data:
        pytest.skip(f"Key not in fixture: {key}")

    E_mc = float(data[key])

    # Build waveform scheme at 1 T/m then scale (waveform stores actual G_amp)
    n_t  = int(round(T_TOTAL / DT_WF)) + 1
    t    = np.arange(n_t) * DT_WF

    if wf_name == "ogse_cosine":
        G = np.zeros((n_t, 3), dtype=np.float32)
        G[:, 2] = (G_max * np.cos(OMEGA * t)).astype(np.float32)
        grad_dir = np.array([[0., 0., 1.]])
    else:  # ogse_rotating
        env = G_max * np.cos(OMEGA * t)
        rot = np.pi / 2.0 * t / T_TOTAL
        G   = np.zeros((n_t, 3), dtype=np.float32)
        G[:, 0] = (env * np.cos(rot)).astype(np.float32)
        G[:, 1] = (env * np.sin(rot)).astype(np.float32)
        grad_dir = np.array([[1.0 / np.sqrt(2.0), 1.0 / np.sqrt(2.0), 0.0]])

    scheme = AcquisitionScheme.from_waveform(
        G[np.newaxis], DT_WF, grad_dir, allow_unrefocused=True)

    diam_m = R_um * 2e-6
    c4     = C4CylinderGaussianPhaseApproximation(
        diffusion_perpendicular=D_PERP, diameter=diam_m)

    E_lm   = c4.signal_lm(scheme, diameter=diam_m, lambda_par=LAMBDA_PAR)
    odf_lm = watson_odf_lm(MU_Z, kappa, l_max=8)
    E_anal = float(np.asarray(dispersed_signal_from_E_lm(E_lm, odf_lm)).flat[0])

    assert abs(E_anal - E_mc) < TOL, (
        f"{wf_name} G={G_max:.2f}T/m R={R_um}µm κ={kappa}: "
        f"analytical={E_anal:.4f}  MC={E_mc:.4f}  "
        f"|ΔE|={abs(E_anal-E_mc):.4f}  tol={TOL}"
    )
